from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Dict, Iterable, List, Optional, Sequence, Set


class UnknownStatError(KeyError):
    pass


class Unit(str, Enum):
    COUNT = "count"
    PERCENT = "percent"
    PERCENT_POINTS = "percent_points"
    MULTIPLIER = "multiplier"
    HP = "hp"
    HP_PER_S = "hp_per_s"
    SECONDS = "seconds"
    WAVES = "waves"
    METERS = "meters"
    PER_SEC = "per_sec"
    DAMAGE = "damage"
    CURRENCY = "currency"
    NONE = "none"


class StatKind(str, Enum):
    BASE = "base"
    DELTA_ADD = "delta_add"
    DELTA_MULT = "delta_mult"
    CAP = "cap"
    DERIVED = "derived"


class StatScope(str, Enum):
    TOWER = "tower"
    WALL = "wall"
    ENEMY = "enemy"
    BOSS = "boss"
    RUN = "run"


class Phase(str, Enum):
    START_OF_RUN = "start_of_run"
    END_OF_RUN = "end_of_run"
    AT_WAVE = "at_wave"


@dataclass(frozen=True)
class StatDef:
    stat_id: str
    display_name: str
    unit: Unit
    kind: StatKind
    scope: StatScope
    allowed_phases: Set[Phase]
    description: Optional[str] = None


class StatRegistry:
    def __init__(self, definitions: Iterable[StatDef]):
        self._defs: Dict[str, StatDef] = {}
        for definition in definitions:
            if definition.stat_id in self._defs:
                raise ValueError(f"Duplicate stat_id in registry: {definition.stat_id}")
            self._defs[definition.stat_id] = definition

    def get(self, stat_id: str) -> StatDef:
        if stat_id not in self._defs:
            raise UnknownStatError(f"Unknown stat_id: {stat_id}")
        return self._defs[stat_id]

    def validate_stat_id(self, stat_id: str) -> None:
        if stat_id not in self._defs:
            raise UnknownStatError(f"Unknown stat_id: {stat_id}")

    def all_defs(self) -> List[StatDef]:
        return sorted(self._defs.values(), key=lambda item: item.stat_id)

    def stat_ids_in_order(self) -> List[str]:
        return list(self._defs.keys())


def default_registry() -> StatRegistry:
    defs: Sequence[StatDef] = [
        StatDef(
            stat_id="tower_hp",
            display_name="Health",
            unit=Unit.HP,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Tower health (base value).",
        ),
        StatDef(
            stat_id="tower_regen",
            display_name="Health Regen",
            unit=Unit.HP_PER_S,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Tower regen rate (base value).",
        ),
        StatDef(
            stat_id="def_pct",
            display_name="Defense %",
            unit=Unit.PERCENT,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Defense percent (base value).",
        ),
        StatDef(
            stat_id="wall_hp",
            display_name="Wall Health",
            unit=Unit.HP,
            kind=StatKind.BASE,
            scope=StatScope.WALL,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Wall health (base value).",
        ),
        StatDef(
            stat_id="wall_regen",
            display_name="Wall Regen",
            unit=Unit.HP_PER_S,
            kind=StatKind.BASE,
            scope=StatScope.WALL,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Wall regen rate (base value).",
        ),
        StatDef(
            stat_id="eals_pct",
            display_name="Enemy Attack Level Skip",
            unit=Unit.PERCENT,
            kind=StatKind.DERIVED,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Enemy attack level skip percent (placeholder).",
        ),
        StatDef(
            stat_id="ehls_pct",
            display_name="Enemy Health Level Skip",
            unit=Unit.PERCENT,
            kind=StatKind.DERIVED,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Enemy health level skip percent (placeholder).",
        ),
        StatDef(
            stat_id="wave_attack_index",
            display_name="Wave Attack Index",
            unit=Unit.WAVES,
            kind=StatKind.DERIVED,
            scope=StatScope.RUN,
            allowed_phases={Phase.AT_WAVE},
            description="Derived attack wave index (placeholder).",
        ),
        StatDef(
            stat_id="wave_health_index",
            display_name="Wave Health Index",
            unit=Unit.WAVES,
            kind=StatKind.DERIVED,
            scope=StatScope.RUN,
            allowed_phases={Phase.AT_WAVE},
            description="Derived health wave index (placeholder).",
        ),
        StatDef(
            stat_id="orb_damage_mult",
            display_name="Orb Damage Multiplier",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description=(
                "Tier BC: orb resistance multiplier from step1 dump "
                "(reference/step1_dump_docs/part2_data/tier_battle_conditions.csv)."
            ),
        ),
        StatDef(
            stat_id="death_ray_damage_mult",
            display_name="Death Ray Damage Multiplier",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description=(
                "Tier BC: death ray resistance multiplier from step1 dump "
                "(reference/step1_dump_docs/part2_data/tier_battle_conditions.csv)."
            ),
        ),
        StatDef(
            stat_id="thorns_damage_mult",
            display_name="Thorns Damage Multiplier",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description=(
                "Tier BC: thorns resistance multiplier from step1 dump "
                "(reference/step1_dump_docs/part2_data/tier_battle_conditions.csv)."
            ),
        ),
        StatDef(
            stat_id="plasma_cannon_damage_mult",
            display_name="Plasma Cannon Damage Multiplier",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description=(
                "Tier BC: plasma cannon resistance multiplier from step1 dump "
                "(reference/step1_dump_docs/part2_data/tier_battle_conditions.csv)."
            ),
        ),
        StatDef(
            stat_id="knockback_mult",
            display_name="Knockback Multiplier",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description=(
                "Tier BC: knockback resistance multiplier from step1 dump "
                "(reference/step1_dump_docs/part2_data/tier_battle_conditions.csv)."
            ),
        ),
        StatDef(
            stat_id="tower_damage",
            display_name="Tower Damage",
            unit=Unit.NONE,
            kind=StatKind.DERIVED,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description=(
                "Effective Paths eDamage output: composed tower damage multiplier stack."
            ),
        ),
        StatDef(
            stat_id="tower_attack_speed",
            display_name="Tower Attack Speed",
            unit=Unit.MULTIPLIER,
            kind=StatKind.DERIVED,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Effective Paths eDamage output: attack speed multiplier.",
        ),
        StatDef(
            stat_id="tower_crit_chance",
            display_name="Tower Crit Chance",
            unit=Unit.PERCENT,
            kind=StatKind.DERIVED,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Effective Paths eDamage output: critical chance.",
        ),
        StatDef(
            stat_id="tower_crit_multiplier",
            display_name="Tower Crit Multiplier",
            unit=Unit.MULTIPLIER,
            kind=StatKind.DERIVED,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Effective Paths eDamage output: expected crit multiplier.",
        ),
        StatDef(
            stat_id="tower_dps",
            display_name="Tower DPS",
            unit=Unit.NONE,
            kind=StatKind.DERIVED,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Effective Paths eDamage output: tower DPS estimate.",
        ),
        StatDef(
            stat_id="workshop_damage",
            display_name="Workshop Damage",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop damage value from WSValues/DVT_Workshop tables.",
        ),
        StatDef(
            stat_id="workshop_attack_speed",
            display_name="Workshop Attack Speed",
            unit=Unit.PER_SEC,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop attack speed value from DVT_Workshop tables.",
        ),
        StatDef(
            stat_id="workshop_critical_chance",
            display_name="Workshop Critical Chance",
            unit=Unit.PERCENT,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop critical chance value from workshop tables (needs authoritative table).",
        ),
        StatDef(
            stat_id="workshop_critical_factor",
            display_name="Workshop Critical Factor",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop critical factor value from DVT_Workshop tables.",
        ),
        StatDef(
            stat_id="workshop_range_meters",
            display_name="Workshop Range",
            unit=Unit.METERS,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop range value from workshop tables (needs authoritative table).",
        ),
        StatDef(
            stat_id="workshop_health",
            display_name="Workshop Health",
            unit=Unit.HP,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop health value from WSValues/DVT_Workshop tables.",
        ),
        StatDef(
            stat_id="workshop_health_regen",
            display_name="Workshop Health Regen",
            unit=Unit.HP_PER_S,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop health regen value from WSValues/DVT_Workshop tables.",
        ),
        StatDef(
            stat_id="workshop_defense_percent",
            display_name="Workshop Defense %",
            unit=Unit.PERCENT,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop defense percent value (needs authoritative table).",
        ),
        StatDef(
            stat_id="workshop_defense_absolute",
            display_name="Workshop Defense Absolute",
            unit=Unit.DAMAGE,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop defense absolute value from WSValues/DVT_Workshop tables.",
        ),
        StatDef(
            stat_id="workshop_thorn_damage",
            display_name="Workshop Thorn Damage",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop thorn damage value (needs authoritative table).",
        ),
        StatDef(
            stat_id="workshop_lifesteal",
            display_name="Workshop Lifesteal",
            unit=Unit.PERCENT,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop lifesteal value from WSValues/DVT_Workshop tables.",
        ),
        StatDef(
            stat_id="workshop_knockback",
            display_name="Workshop Knockback",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop knockback value (needs authoritative table).",
        ),
        StatDef(
            stat_id="workshop_orbs",
            display_name="Workshop Orbs",
            unit=Unit.COUNT,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop orbs count value (needs authoritative table).",
        ),
        StatDef(
            stat_id="workshop_shockwave",
            display_name="Workshop Shockwave",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop shockwave value (needs authoritative table).",
        ),
        StatDef(
            stat_id="workshop_land_mine",
            display_name="Workshop Land Mine",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop land mine value (needs authoritative table).",
        ),
        StatDef(
            stat_id="workshop_death_defy",
            display_name="Workshop Death Defy",
            unit=Unit.PERCENT,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop death defy chance (needs authoritative table).",
        ),
        StatDef(
            stat_id="workshop_wall_health",
            display_name="Workshop Wall Health",
            unit=Unit.HP,
            kind=StatKind.BASE,
            scope=StatScope.WALL,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop wall health value from DVT_Workshop tables.",
        ),
        StatDef(
            stat_id="workshop_wall_regen",
            display_name="Workshop Wall Regen",
            unit=Unit.HP_PER_S,
            kind=StatKind.BASE,
            scope=StatScope.WALL,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop wall regen value (needs authoritative table).",
        ),
        StatDef(
            stat_id="workshop_wall_fortification",
            display_name="Workshop Wall Fortification",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.WALL,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop wall fortification value (needs authoritative table).",
        ),
        StatDef(
            stat_id="workshop_cash_bonus",
            display_name="Workshop Cash Bonus",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop cash bonus value from DVT_Workshop tables.",
        ),
        StatDef(
            stat_id="workshop_cash_per_wave",
            display_name="Workshop Cash Per Wave",
            unit=Unit.CURRENCY,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop cash per wave value (needs authoritative table).",
        ),
        StatDef(
            stat_id="workshop_coins_per_kill_bonus",
            display_name="Workshop Coins Per Kill Bonus",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop coins per kill bonus value from DVT_Workshop tables.",
        ),
        StatDef(
            stat_id="workshop_coins_per_wave",
            display_name="Workshop Coins Per Wave",
            unit=Unit.CURRENCY,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop coins per wave value (needs authoritative table).",
        ),
        StatDef(
            stat_id="workshop_free_upgrades",
            display_name="Workshop Free Upgrades",
            unit=Unit.PERCENT,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop free upgrades value from DVT_Workshop tables.",
        ),
        StatDef(
            stat_id="workshop_interest",
            display_name="Workshop Interest",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop interest value (needs authoritative table).",
        ),
        StatDef(
            stat_id="workshop_recovery_packages",
            display_name="Workshop Recovery Packages",
            unit=Unit.PERCENT,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop recovery package value from DVT_Workshop tables.",
        ),
        StatDef(
            stat_id="workshop_max_recovery",
            display_name="Workshop Max Recovery",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop max recovery value (needs authoritative table).",
        ),
        StatDef(
            stat_id="workshop_enemy_level_skip",
            display_name="Workshop Enemy Level Skip",
            unit=Unit.PERCENT,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop enemy level skip value from DVT_Workshop tables.",
        ),
        StatDef(
            stat_id="workshop_damage_per_meter",
            display_name="Workshop Damage Per Meter",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop damage per meter value from WSValues/DVT_Workshop tables.",
        ),
        StatDef(
            stat_id="workshop_super_crit_mult",
            display_name="Workshop Super Crit Multiplier",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop super crit multiplier value from DVT_Workshop tables.",
        ),
        StatDef(
            stat_id="workshop_land_mine_damage",
            display_name="Workshop Land Mine Damage",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop land mine damage value from DVT_Workshop tables.",
        ),
        StatDef(
            stat_id="workshop_orb_size",
            display_name="Workshop Orb Size",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop orb size value from DVT_Workshop tables.",
        ),
        StatDef(
            stat_id="workshop_cells_per_kill_bonus",
            display_name="Workshop Cells Per Kill Bonus",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop cells per kill bonus value from DVT_Workshop tables.",
        ),
        StatDef(
            stat_id="workshop_rend_armor",
            display_name="Workshop Rend Armor",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop rend armor value from DVT_Workshop tables.",
        ),
        StatDef(
            stat_id="workshop_multishot_chance",
            display_name="Workshop Multishot Chance",
            unit=Unit.PERCENT,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop multishot chance from DVT_WS_VALUE.",
        ),
        StatDef(
            stat_id="workshop_multishot_targets",
            display_name="Workshop Multishot Targets",
            unit=Unit.COUNT,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop multishot targets from DVT_WS_VALUE.",
        ),
        StatDef(
            stat_id="workshop_rapid_fire_chance",
            display_name="Workshop Rapid Fire Chance",
            unit=Unit.PERCENT,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop rapid fire chance from DVT_WS_VALUE.",
        ),
        StatDef(
            stat_id="workshop_rapid_fire_duration",
            display_name="Workshop Rapid Fire Duration",
            unit=Unit.SECONDS,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop rapid fire duration from DVT_WS_VALUE.",
        ),
        StatDef(
            stat_id="workshop_bounce_shot_chance",
            display_name="Workshop Bounce Shot Chance",
            unit=Unit.PERCENT,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop bounce shot chance from DVT_WS_VALUE.",
        ),
        StatDef(
            stat_id="workshop_bounce_shot_targets",
            display_name="Workshop Bounce Shot Targets",
            unit=Unit.COUNT,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop bounce shot targets from DVT_WS_VALUE.",
        ),
        StatDef(
            stat_id="workshop_bounce_shot_range",
            display_name="Workshop Bounce Shot Range",
            unit=Unit.NONE,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop bounce shot range (unsupported; EP returns empty).",
        ),
        StatDef(
            stat_id="workshop_super_crit_chance",
            display_name="Workshop Super Crit Chance",
            unit=Unit.PERCENT,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop super critical chance from DVT_WS_VALUE.",
        ),
        StatDef(
            stat_id="workshop_super_crit_mult_alt",
            display_name="Workshop Super Crit Mult",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop super critical multiplier from DVT_WS_VALUE.",
        ),
        StatDef(
            stat_id="workshop_rend_armor_chance",
            display_name="Workshop Rend Armor Chance",
            unit=Unit.PERCENT,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop rend armor chance from DVT_WS_VALUE.",
        ),
        StatDef(
            stat_id="workshop_rend_armor_mult",
            display_name="Workshop Rend Armor Mult",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop rend armor multiplier from DVT_WS_VALUE.",
        ),
        StatDef(
            stat_id="workshop_knockback_chance",
            display_name="Workshop Knockback Chance",
            unit=Unit.PERCENT,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop knockback chance from DVT_WS_VALUE.",
        ),
        StatDef(
            stat_id="workshop_knockback_force",
            display_name="Workshop Knockback Force",
            unit=Unit.NONE,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop knockback force from DVT_WS_VALUE.",
        ),
        StatDef(
            stat_id="workshop_shockwave_size",
            display_name="Workshop Shockwave Size",
            unit=Unit.NONE,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop shockwave size from DVT_WS_VALUE.",
        ),
        StatDef(
            stat_id="workshop_shockwave_frequency",
            display_name="Workshop Shockwave Frequency",
            unit=Unit.NONE,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop shockwave frequency from DVT_WS_VALUE.",
        ),
        StatDef(
            stat_id="workshop_land_mine_chance",
            display_name="Workshop Land Mine Chance",
            unit=Unit.PERCENT,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop land mine chance from DVT_WS_VALUE.",
        ),
        StatDef(
            stat_id="workshop_land_mine_radius",
            display_name="Workshop Land Mine Radius",
            unit=Unit.NONE,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop land mine radius from DVT_WS_VALUE.",
        ),
        StatDef(
            stat_id="workshop_orb_speed",
            display_name="Workshop Orb Speed",
            unit=Unit.NONE,
            kind=StatKind.BASE,
            scope=StatScope.TOWER,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop orb speed from DVT_WS_VALUE.",
        ),
        StatDef(
            stat_id="workshop_recovery_amount",
            display_name="Workshop Recovery Amount",
            unit=Unit.NONE,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop recovery amount from DVT_WS_VALUE.",
        ),
        StatDef(
            stat_id="workshop_package_chance",
            display_name="Workshop Package Chance",
            unit=Unit.PERCENT,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop package chance from DVT_WS_VALUE.",
        ),
        StatDef(
            stat_id="workshop_wall_rebuild",
            display_name="Workshop Wall Rebuild",
            unit=Unit.NONE,
            kind=StatKind.BASE,
            scope=StatScope.WALL,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop wall rebuild from DVT_WS_VALUE.",
        ),
        StatDef(
            stat_id="workshop_enemy_attack_level_skip",
            display_name="Workshop Enemy Attack Level Skip",
            unit=Unit.PERCENT,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop enemy attack level skip from DVT_WS_VALUE.",
        ),
        StatDef(
            stat_id="workshop_enemy_health_level_skip",
            display_name="Workshop Enemy Health Level Skip",
            unit=Unit.PERCENT,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop enemy health level skip from DVT_WS_VALUE.",
        ),
        StatDef(
            stat_id="workshop_free_attack_upgrade",
            display_name="Workshop Free Attack Upgrade",
            unit=Unit.PERCENT,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop free attack upgrade from DVT_WS_VALUE.",
        ),
        StatDef(
            stat_id="workshop_free_defense_upgrade",
            display_name="Workshop Free Defense Upgrade",
            unit=Unit.PERCENT,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop free defense upgrade from DVT_WS_VALUE.",
        ),
        StatDef(
            stat_id="workshop_free_utility_upgrade",
            display_name="Workshop Free Utility Upgrade",
            unit=Unit.PERCENT,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop free utility upgrade from DVT_WS_VALUE.",
        ),
        StatDef(
            stat_id="workshop_max_amount",
            display_name="Workshop Max Amount",
            unit=Unit.NONE,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Workshop max amount (unsupported; EP lacks numeric rule).",
        ),
        StatDef(
            stat_id="uw_golden_tower_duration",
            display_name="UW Golden Tower Duration",
            unit=Unit.SECONDS,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Golden Tower duration track from Data_Val_Tables.csv.",
        ),
        StatDef(
            stat_id="uw_black_hole_consume",
            display_name="UW Black Hole Consume",
            unit=Unit.NONE,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Black Hole consume track from Data_Val_Tables.csv.",
        ),
        StatDef(
            stat_id="uw_chain_lightning_damage",
            display_name="UW Chain Lightning Damage",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Chain Lightning damage track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_chain_lightning_quantity",
            display_name="UW Chain Lightning Quantity",
            unit=Unit.COUNT,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Chain Lightning quantity track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_chain_lightning_chance",
            display_name="UW Chain Lightning Chance",
            unit=Unit.PERCENT,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Chain Lightning chance track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_chain_lightning_smite",
            display_name="UW Chain Lightning Smite",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Chain Lightning smite track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_smart_missiles_damage",
            display_name="UW Smart Missiles Damage",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Smart Missiles damage track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_smart_missiles_quantity",
            display_name="UW Smart Missiles Quantity",
            unit=Unit.COUNT,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Smart Missiles quantity track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_smart_missiles_cooldown",
            display_name="UW Smart Missiles Cooldown",
            unit=Unit.SECONDS,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Smart Missiles cooldown track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_smart_missiles_cover_fire",
            display_name="UW Smart Missiles Cover Fire",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Smart Missiles cover fire track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_death_wave_damage",
            display_name="UW Death Wave Damage",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Death Wave damage track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_death_wave_quantity",
            display_name="UW Death Wave Quantity",
            unit=Unit.COUNT,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Death Wave quantity track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_death_wave_cooldown",
            display_name="UW Death Wave Cooldown",
            unit=Unit.SECONDS,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Death Wave cooldown track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_death_wave_kill_wall",
            display_name="UW Death Wave Kill Wall",
            unit=Unit.COUNT,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Death Wave kill wall track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_chrono_field_duration",
            display_name="UW Chrono Field Duration",
            unit=Unit.SECONDS,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Chrono Field duration track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_chrono_field_speed_reduction",
            display_name="UW Chrono Field Speed Reduction",
            unit=Unit.PERCENT,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Chrono Field speed reduction track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_chrono_field_cooldown",
            display_name="UW Chrono Field Cooldown",
            unit=Unit.SECONDS,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Chrono Field cooldown track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_chrono_field_chrono_loop",
            display_name="UW Chrono Field Chrono Loop",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Chrono Field chrono loop track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_inner_land_mines_damage",
            display_name="UW Inner Land Mines Damage",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Inner Land Mines damage track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_inner_land_mines_quantity",
            display_name="UW Inner Land Mines Quantity",
            unit=Unit.COUNT,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Inner Land Mines quantity track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_inner_land_mines_cooldown",
            display_name="UW Inner Land Mines Cooldown",
            unit=Unit.SECONDS,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Inner Land Mines cooldown track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_inner_land_mines_charged_mines",
            display_name="UW Inner Land Mines Charged Mines",
            unit=Unit.COUNT,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Inner Land Mines charged mines track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_golden_tower_multiplier",
            display_name="UW Golden Tower Multiplier",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Golden Tower multiplier track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_golden_tower_cooldown",
            display_name="UW Golden Tower Cooldown",
            unit=Unit.SECONDS,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Golden Tower cooldown track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_golden_tower_golden_combo",
            display_name="UW Golden Tower Golden Combo",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Golden Tower golden combo track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_poison_swamp_damage",
            display_name="UW Poison Swamp Damage",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Poison Swamp damage track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_poison_swamp_duration",
            display_name="UW Poison Swamp Duration",
            unit=Unit.SECONDS,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Poison Swamp duration track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_poison_swamp_cooldown",
            display_name="UW Poison Swamp Cooldown",
            unit=Unit.SECONDS,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Poison Swamp cooldown track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_poison_swamp_death_creep",
            display_name="UW Poison Swamp Death Creep",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Poison Swamp death creep track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_black_hole_size",
            display_name="UW Black Hole Size",
            unit=Unit.METERS,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Black Hole size track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_black_hole_duration",
            display_name="UW Black Hole Duration",
            unit=Unit.SECONDS,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Black Hole duration track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_black_hole_cooldown",
            display_name="UW Black Hole Cooldown",
            unit=Unit.SECONDS,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Black Hole cooldown track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_spotlight_multiplier",
            display_name="UW Spotlight Multiplier",
            unit=Unit.MULTIPLIER,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Spotlight multiplier track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_spotlight_angle",
            display_name="UW Spotlight Angle",
            unit=Unit.METERS,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Spotlight angle track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_spotlight_quantity",
            display_name="UW Spotlight Quantity",
            unit=Unit.COUNT,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Spotlight quantity track from uw_tables_v2_1_2.zip.",
        ),
        StatDef(
            stat_id="uw_spotlight_light_range",
            display_name="UW Spotlight Light Range",
            unit=Unit.METERS,
            kind=StatKind.BASE,
            scope=StatScope.RUN,
            allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
            description="Spotlight light range track from uw_tables_v2_1_2.zip.",
        ),
    ]
    uw_cost_stats = [
        ("uw_chain_lightning_damage", "UW Chain Lightning Damage"),
        ("uw_chain_lightning_quantity", "UW Chain Lightning Quantity"),
        ("uw_chain_lightning_chance", "UW Chain Lightning Chance"),
        ("uw_chain_lightning_smite", "UW Chain Lightning Smite"),
        ("uw_smart_missiles_damage", "UW Smart Missiles Damage"),
        ("uw_smart_missiles_quantity", "UW Smart Missiles Quantity"),
        ("uw_smart_missiles_cooldown", "UW Smart Missiles Cooldown"),
        ("uw_smart_missiles_cover_fire", "UW Smart Missiles Cover Fire"),
        ("uw_death_wave_damage", "UW Death Wave Damage"),
        ("uw_death_wave_quantity", "UW Death Wave Quantity"),
        ("uw_death_wave_cooldown", "UW Death Wave Cooldown"),
        ("uw_death_wave_kill_wall", "UW Death Wave Kill Wall"),
        ("uw_chrono_field_duration", "UW Chrono Field Duration"),
        ("uw_chrono_field_speed_reduction", "UW Chrono Field Speed Reduction"),
        ("uw_chrono_field_cooldown", "UW Chrono Field Cooldown"),
        ("uw_chrono_field_chrono_loop", "UW Chrono Field Chrono Loop"),
        ("uw_inner_land_mines_damage", "UW Inner Land Mines Damage"),
        ("uw_inner_land_mines_quantity", "UW Inner Land Mines Quantity"),
        ("uw_inner_land_mines_cooldown", "UW Inner Land Mines Cooldown"),
        ("uw_inner_land_mines_charged_mines", "UW Inner Land Mines Charged Mines"),
        ("uw_golden_tower_multiplier", "UW Golden Tower Multiplier"),
        ("uw_golden_tower_duration", "UW Golden Tower Duration"),
        ("uw_golden_tower_cooldown", "UW Golden Tower Cooldown"),
        ("uw_golden_tower_golden_combo", "UW Golden Tower Golden Combo"),
        ("uw_poison_swamp_damage", "UW Poison Swamp Damage"),
        ("uw_poison_swamp_duration", "UW Poison Swamp Duration"),
        ("uw_poison_swamp_cooldown", "UW Poison Swamp Cooldown"),
        ("uw_poison_swamp_death_creep", "UW Poison Swamp Death Creep"),
        ("uw_black_hole_size", "UW Black Hole Size"),
        ("uw_black_hole_duration", "UW Black Hole Duration"),
        ("uw_black_hole_cooldown", "UW Black Hole Cooldown"),
        ("uw_black_hole_consume", "UW Black Hole Consume"),
        ("uw_spotlight_multiplier", "UW Spotlight Multiplier"),
        ("uw_spotlight_angle", "UW Spotlight Angle"),
        ("uw_spotlight_quantity", "UW Spotlight Quantity"),
        ("uw_spotlight_light_range", "UW Spotlight Light Range"),
    ]
    expanded = list(defs)
    for stat_id, display_name in uw_cost_stats:
        expanded.append(
            StatDef(
                stat_id=f"{stat_id}_next_cost",
                display_name=f"{display_name} Next Cost",
                unit=Unit.CURRENCY,
                kind=StatKind.BASE,
                scope=StatScope.RUN,
                allowed_phases={Phase.START_OF_RUN, Phase.END_OF_RUN},
                description="Next upgrade cost from uw_tables_v2_1_2.zip.",
            )
        )
    return StatRegistry(expanded)
